name = "ArrayPadding"
uuid = "fe5ef43c-4912-423d-9170-4bd5cb6a013a"
authors = ["Paul Shen <pxshen@alumni.stanford.edu>"]
version = "0.1.11"

[deps]
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Functors = "0.4"
Lazy = "0.15"
LazyArrays = "1.8"
Zygote = "0.6"
julia = "1.9"
