name = "ArrayPadding"
uuid = "fe5ef43c-4912-423d-9170-4bd5cb6a013a"
authors = ["Paul Shen <pxshen@alumni.stanford.edu>"]
version = "0.1.19"

[deps]
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"

[compat]
Functors = "0.4"
Lazy = "0.15"
julia = "1.9"
