name = "ArrayPadding"
uuid = "fe5ef43c-4912-423d-9170-4bd5cb6a013a"
authors = ["Paul Shen <pxshen@alumni.stanford.edu>"]
version = "1.0.4"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
CUDAExt = "CUDA"

[compat]
Zygote= "0.6,0.7,1"
CUDA = "5,6,7,8,9,10,11,12"
Statistics = "1,2,3"
julia = "1,2,3"
